/**
 * TypeScript version of Agent Payments Protocol mandate types
 *
 * Source: ../../src/ap2/types/mandate.py
 * Last synced: 2025-11-10
 *
 * Copyright 2025 Google LLC
 * Licensed under the Apache License, Version 2.0
 *
 * Contains the definitions of the Agent Payments Protocol mandates.
 */

import type { PaymentItem, PaymentRequest, PaymentResponse } from './paymentRequest';

export const CART_MANDATE_DATA_KEY = "ap2.mandates.CartMandate";
export const INTENT_MANDATE_DATA_KEY = "ap2.mandates.IntentMandate";
export const PAYMENT_MANDATE_DATA_KEY = "ap2.mandates.PaymentMandate";

/**
 * Represents the user's purchase intent.
 *
 * These are the initial fields utilized in the human-present flow. For
 * human-not-present flows, additional fields will be added to this mandate.
 *
 * Source: mandate.py:32-76
 */
export interface IntentMandate {
  /**
   * If false, the agent can make purchases on the user's behalf once all
   * purchase conditions have been satisfied. This must be true if the
   * intent mandate is not signed by the user.
   */
  user_cart_confirmation_required: boolean;
  /**
   * The natural language description of the user's intent. This is
   * generated by the shopping agent, and confirmed by the user. The
   * goal is to have informed consent by the user.
   *
   * Example: "High top, old school, red basketball shoes"
   */
  natural_language_description: string;
  /**
   * Merchants allowed to fulfill the intent. If not set, the shopping
   * agent is able to work with any suitable merchant.
   */
  merchants?: string[];
  /**
   * A list of specific product SKUs. If not set, any SKU is allowed.
   */
  skus?: string[];
  /**
   * If true, items must be refundable.
   */
  requires_refundability?: boolean;
  /**
   * When the intent mandate expires, in ISO 8601 format.
   */
  intent_expiry: string;
}

/**
 * The detailed contents of a cart.
 *
 * This object is signed by the merchant to create a CartMandate.
 *
 * Source: mandate.py:79-104
 */
export interface CartContents {
  /** A unique identifier for this cart. */
  id: string;
  /**
   * If true, the merchant requires the user to confirm the cart before
   * the purchase can be completed.
   */
  user_cart_confirmation_required: boolean;
  /**
   * The W3C PaymentRequest object to initiate payment. This contains the
   * items being purchased, prices, and the set of payment methods
   * accepted by the merchant for this cart.
   */
  payment_request: PaymentRequest;
  /** When this cart expires, in ISO 8601 format. */
  cart_expiry: string;
  /** The name of the merchant. */
  merchant_name: string;
}

/**
 * A cart whose contents have been digitally signed by the merchant.
 *
 * This serves as a guarantee of the items and price for a limited time.
 *
 * Source: mandate.py:107-134
 */
export interface CartMandate {
  /** The contents of the cart. */
  contents: CartContents;
  /**
   * A base64url-encoded JSON Web Token (JWT) that digitally
   * signs the cart contents, guaranteeing its authenticity and integrity:
   *
   * 1. Header includes the signing algorithm and key ID.
   * 2. Payload includes:
   *    - iss, sub, aud: Identifiers for the merchant (issuer)
   *      and the intended recipient (audience), like a payment processor.
   *    - iat, exp: Timestamps for the token's creation and its
   *      short-lived expiration (e.g., 5-15 minutes) to enhance security.
   *    - jti: Unique identifier for the JWT to prevent replay attacks.
   *    - cart_hash: A secure hash of the CartMandate, ensuring
   *      integrity. The hash is computed over the canonical JSON
   *      representation of the CartContents object.
   * 3. Signature: A digital signature created with the merchant's private
   *    key. It allows anyone with the public key to verify the token's
   *    authenticity and confirm that the payload has not been tampered with.
   *
   * The entire JWT is base64url encoded to ensure safe transmission.
   *
   * Example: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjIwMjQwOTA..."
   */
  merchant_authorization?: string;
}

/**
 * The data contents of a PaymentMandate.
 *
 * Source: mandate.py:137-162
 */
export interface PaymentMandateContents {
  /** A unique identifier for this payment mandate. */
  payment_mandate_id: string;
  /** A unique identifier for the payment request. */
  payment_details_id: string;
  /** The total payment amount. */
  payment_details_total: PaymentItem;
  /**
   * The payment response containing details of the payment method chosen
   * by the user.
   */
  payment_response: PaymentResponse;
  /** Identifier for the merchant. */
  merchant_agent: string;
  /**
   * The date and time the mandate was created, in ISO 8601 format.
   * Defaults to current UTC time.
   */
  timestamp: string;
}

/**
 * Contains the user's instructions & authorization for payment.
 *
 * While the Cart and Intent mandates are required by the merchant to fulfill the
 * order, separately the protocol provides additional visibility into the agentic
 * transaction to the payments ecosystem. For this purpose, the PaymentMandate
 * (bound to Cart/Intent mandate but containing separate information) may be
 * shared with the network/issuer along with the standard transaction
 * authorization messages. The goal of the PaymentMandate is to help the
 * network/issuer build trust into the agentic transaction.
 *
 * Source: mandate.py:165-200
 */
export interface PaymentMandate {
  /** The data contents of the payment mandate. */
  payment_mandate_contents: PaymentMandateContents;
  /**
   * This is a base64_url-encoded verifiable presentation of a verifiable
   * credential signing over the cart_mandate and payment_mandate_hashes.
   *
   * For example an sd-jwt-vc would contain:
   * - An issuer-signed jwt authorizing a 'cnf' claim
   * - A key-binding jwt with the claims:
   *   - "aud": ...
   *   - "nonce": ...
   *   - "sd_hash": hash of the issuer-signed jwt
   *   - "transaction_data": an array containing the secure hashes of
   *     CartMandate and PaymentMandateContents.
   *
   * Example: "eyJhbGciOiJFUzI1NksiLCJraWQiOiJkaWQ6ZXhhbXBsZ..."
   */
  user_authorization?: string;
}
